# HTTP Server
[server]
    Address     = ":8199"
    ServerRoot  = ""
    ServerAgent = "gf-app"

    LogPath     = "./storage/logs/app"           # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
    LogStdout           = true               # 日志是否输出到终端。默认为true
    ErrorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    ErrorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
    ErrorLogPattern     = "error-{Y-m-d}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    AccessLogEnabled    = false              # 是否记录访问日志。默认为false
    AccessLogPattern    = "access-{Y-m-d}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
    Language = "cn"

# Logger.
[logger]
    Path                 = "./storage/logs"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
    File                 = "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
    Level                = "all"
    Stdout               = false
    Prefix               = ""            # 日志内容输出前缀。默认为空
    CtxKeys              = []            # Context上下文变量名称，自动打印Context的变量到日志中。默认为空
    HeaderPrint          = true          # 是否打印日志的头信息。默认true
    StdoutPrint          = true          # 日志是否同时输出到终端。默认true
    RotateSize           = 0             # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    RotateExpire         = 0             # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    RotateBackupLimit    = 0             # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    RotateBackupExpire   = 0             # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    RotateBackupCompress = 0             # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
    RotateCheckInterval  = "1h"          # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时

# Database.
[database]
    link  = "root:123456@tcp(127.0.0.1:3306)/ginpp?charset=utf8mb4&parseTime=True&loc=Local"
    debug = true

# Database logger.
[database.logger]
    Path   = "./storage/logs/database"
    Level  = "all"
    Stdout = true
    File   = "sql-{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"

[i18n]
    Default = "cn"